### PR TITLE
Modern XP system setting

### PR DESCRIPTION
**Pull request by GarOfMeridian**
Comes with a setting to switch between classic and modern XP, as well as
a setting to 'cap' modern experience to a player's current HP to tightly
model classic advancement rates.

Good option for servers running Meridian 59 that want an XP system
most players will immediately recognize.

### CODE REVIEW

**Comment by treymd** [comment]
Would like to see settings for XP needed and XP granted in some way.

**Comment by GarOfMeridian** [comment]
Sure, what kind of settings exactly?

**Comment by Daenks** [comment]
XP needed would be how much is needed for the next tougher, that could be a scale (%) option or what have you.
XP granted would be how much is given per kill, which could also be a percent scale factor.

**Comment by Maikeljr** [comment]
This would take away a lot of the guesswork/randomness/distrust of the current hp tougher system.

**Pull request merged**
