### PR TITLE
Visual Studio 2008 SP1 Solution for Meridian 59

### PR DESCRIPTION
**Pull request by Daenks**
This is a work in progress.

Update 3/12/15:
Everything compiles, but adjustments need to be made for efficiency, and to catch up with makefile changes that have been made since the original pull was opened. 

- [X] blakserv
- [X] ALL .\util projects
- [X] clientd3d
- [X] modules
- [x] bkod compiled
- [X]] bkod diff engine
- [X] creation of kod files using the above
- [X] makebgf
- [X] Butil
- [ ] BBgun
- [ ] Keybind

### CODE REVIEW

**Comment by skittles1** [comment]
Should we upgrade this to VS 2013 and then merge to the repo?

**Comment by CyberBill** [comment]
I noticed that there isn't anything from the modules directory being built in these projects/solutions - for example the init.dll file should be built from modules/init.  I think there are also some hard coded directories (C:\Meridian59-master) in there that may need to be changed to relative directories.

I'm still very much learning how github works, so I may not have a good workflow for searching through these requests. :)

**Comment by Daenks** [comment]
I'll address these issues and also try and upgrade it to VS2013

**Comment by skittles1** [comment]
Have adapted this pull request (and CyberBill's VS branch) into a solution for 103 here: #1010

**Comment by skittles1** [comment]
Closing, VS solution in #1010

**Pull request closed without merging**
