### PR TITLE
Knights Helm

### PR DESCRIPTION
**Pull request by TheDiggie**
New helmet including new art for it
has 3 armor -10 sp 50 defense and is a little heavier than a normal helm

### CODE REVIEW

**Comment by skittles1** [comment]
"Made of solid steel plates this helmet is far more effective then a padded helmet."

Should be something like (split over two lines):

"Crafted from solid steel plates, this helm offers far more protection than a padded helmet."

Also please squash those two commits and give the resulting commit a meaningful name (e.g. Added knights helm bgf and code).

**Comment by TheDiggie** [comment]
Wasnt aware the shield had a '

**Comment by M59Gar** [comment]
Didn't see anyone mention this, but 3 armor is a **lot.** Combined with Gort, Jonas Shield, Knight's Shield, and Plate Armor, we're looking at 15 max damage then reduced by 13 armor. All purely physical mobs are going to be doing very little damage. Average ~8, whether it's a pogg king or a daemon. Combined with 50 defense and 5% slash resistance, this helmet is absolutely stellar.

If that's intended, I'm sure the game won't break, but this will definitely be a required item for most players. The defense of leather armor, half again the armor of plate, and another 5% slash resistance to resist the best melee weapon in the game - in a helmet slot, with no tension with other items, since it's strictly better than simple helms / masks. We will simply all be using these tomorrow.

Art is friggin' awesome :)

**Comment by TheDiggie** [comment]
Forgot to add magic weakness to balance it but slash resist isnt as useful as you would assume. If you would pvp u would see that pvp is bows+mystics+nerus+spells scims aint used as much as 101

**Comment by M59Gar** [comment]
Right, scimitar (the highest damage melee weapon by far) is out of favor because of the high prevalence of slash resistance on armors like chain. Even more slash resistance, like on a helm, just compounds that issue. This 5% won't change anything, but we'll have to keep that in mind for some future armor rebalance.

**Comment by TheDiggie** [comment]
Axe does more damage then scim :p

**Comment by M59Gar** [comment]
Scimitar is pretty much literally axe but with 1 higher base damage. They're both slashing, same range, same stat, etc.

**Comment by tyras2** [comment]
Is it possible to take a look at the artworks here at github?

**Comment by TheDiggie** [comment]
Dont believe so

**Comment by TheDiggie** [comment]
https://i.imgur.com/TbRphfH.jpg

**Comment by tyras2** [comment]
Awesome, greate work @TheDiggie

**Comment by Maikeljr** [comment]
I like the helm, but I really think we need to put more emphasis on balancing armors and damage like Gar is hinting at. People don't use highest damage weapon in the game because the balance isn't there to support it, not just because of the shorter range.

**Comment by TheDiggie** [comment]
Good. This pull is about adding a new helm not rebalancing armor or weapons. 

So it seems everyone likes it :)

**Comment by M59Gar** [comment]
The addition of a new helm is actually a change in the balance of armor and weapons. Although I don't see an actual addition to loot tables here. I'm 100% in favor of adding just a plain buttload of weapons, armor, gear, items, whatever into the game's resources. It's really only when they become accessible to players that we have to really analyze things

**Comment by TheDiggie** [comment]
Yea its good to put the item its self in one pull and the drop or how ev you obtain it in another, that way if theres an issue with how u get it the item can still go in game.

**Pull request merged**
