### PR TITLE
Lower cast timer on blink

### PR DESCRIPTION
**Pull request by TheDiggie**

### CODE REVIEW

**Comment by GarOfMeridian** [comment]
Is this going in? I think it's a good idea. The long cast time doesn't really accomplish much these days.

**Comment by skittles1** [comment]
I don't think he was serious about this, blink was never intended as a PvP teleport spell (beyond the odd screen/scenario where you get 10 sec to make this kind of move) and this change would facilitate that.

**Comment by TheDiggie** [comment]
Its good for getting out of spore and catching people in the wild when the blink position is in your favor. 

But yea id like to see this ingame :)

**Comment by M59Gar** [comment]
5 second cast time allows you to blind the enemy sporeburster and then blink out assuming you didn't foolishly move.

**Comment by TheDiggie** [comment]
Yea it would be great agiAnst web and spore

**Pull request closed without merging**
