### PR TITLE
Add multi-language support for resources to compiler, server and client. Add proper C-style for and do-while loops, switch-case and elseif statements to kod. Add pre/post increment-decrement operators.

### PR DESCRIPTION
**Pull request by skittles1**
### Language/resource changes

This pull request adds support for 184 different languages to kod. The compiler looks for a language identifier string (ISO 639-1, e.g. de, ko, sv) and if present the resource string is stored at that position in an array of const_type in the resource_type struct. If no language ID string is present, the English one is assigned by default. Multiple language resources can be defined for the same resource name, as long as they are defined in the same class (same name in different classes will throw an error to help prevent mistakes).

Resources can now be added to a separate file which can be added as an include in the resources: section of the kod code, with the same syntax as other include directives. Support has been added for kod recompilation if a file with the extension .lkod and the same filename is modified, but include files with other names will not cause a recompilation if modified (i.e. the kod file itself should be touched to force nmake to recompile it). The included file must end with a blank line.

The client has a new menu in the toolbar, Language, in which the user can select which display language they would like to use out of the available languages. When the client reads in resources from the rsc or rsb files, it keeps track of which languages have been seen to later populate this menu (so one string for a language would allow that language to be selected). If a language is selected but not all resources are present for that language, it will default to English. Menu example: http://i.imgur.com/uyTJa3R.png. This menu will likely be moved out of the top level in the future, but for now I would like it to have visibility among players (who often do not read update notes).

The StringContain and StringEqual C functions will perform string comparisons using every available language if a resource is passed in as one of the parameters, so that the server can successfully match both English and German commands to the correct resource. Other string-handling C functions use the server's language choice, settable using the Language config field (integer, same values as the language ID table). The command for this is:

```
set config int [Resource] language 1
```

for German, and:

```
set config int [Resource] language 0
```

for English (the default).

Resource example:

```
object_name_rsc = "something"
object_name_rsc = de "etwas"
```

make_resource now adds its (new) completed resources to the resource list for the current class, and when each new resource is created it is first checked against this list. If a duplicate resource ID is encountered, the appropriate language ID (resource array position) is checked and if a string with the same language ID is already present, an error is thrown. New resources are returned to the parser, ones that existed already are not.
### Other compiler changes

Several other new features have been added to the compiler.
#### pre/post increment/decrement operators

Syntax: i++, --i.
Pre-inc/decrement increments or decrements the value of the variable by 1, assigns it to the variable then uses the new value in the expression. Post-inc/decrement uses the old value of the variable in the expression, but increments or decrements the variable by 1 after it is used.
#### for i in list changed to foreach in list

The keyword for list iteration has been changed from "for" to "foreach". "for" will no longer work in this context, to remove any future confusion with the new for loop.
#### C-style for loop

Syntax: for(assignments; expression; assignments) { statements }
Any of these fields can be blank (i.e. for(;;){}). Multiple comma-separated assignments can be performed in either assignment field. The first field of assignments are performed prior to executing the loop or checking the expression, the second field after the loop has executed (i.e. iteration).
#### C-style do-while loop

Syntax: do{statements} while expression;
Same as a while loop, except the statements inside the loop are performed once before the expression is checked.
#### C-style switch-case statement

Syntax: switch(expression) { case expression: statements }
Works the same as in C - the value of the expression in the switch is matched to that in the cases. Default can also be used (with no expression) and is checked last. Break will exit the switch statement (as will continue) and the absence of a break will cause fallthrough to the next case (or the default) in order of how the code is written (i.e. a default placed in the middle of a block of cases with no break will fallthrough to the next case, even though the default is the last evaluation checked).
#### else if statement

Syntax: if expression { statements } else if expression {statements } else { statements }
Works as might be expected, expressions are checked in order and if successful, no other expressions are checked. "else if" cannot come after an "else", and the terminal "else" is optional.
### Message and call timing/blakod interpreting performance

Code has been added to track run time on every C call and kod message executed. This uses QueryPerformanceCounter for accurate microsecond or better timing. The timing can be activated using the "Timecalls" server config (boolean) and is off by default due to incompatibility with Amazon's VMs (a QPC call on the VM requires ~4 microseconds, unacceptable for tracking every call). Existing timing of top-level messages and overall interpreting time has been upgraded to use microseconds instead of milliseconds, as keeping track of interpreting time in milliseconds is inaccurate. The QPC overhead exists for this also, but is unavoidable in this case.
Two config checks have been removed from the InterpretAtMessage function (DEBUG_INITLOCALS and BLAKOD_MAX_STATEMENTS). The max statements config option is now a define. The removal of both config checks reduces interpreting time by ~35%.
#### RSC format changes

Previous RSC format:
RSC header bytes (0x52, 0x53, 0x43, 0x01), RSC_VERSION, num_resources,
RSC_ID, STRING, RSC_ID, STRING...

New RSC format:
RSB header bytes (0x52, 0x53, 0x43, 0x01), RSC_VERSION, num_resources,
RSC_ID, LANGUAGE_ID, STRING, RSC_ID, LANGUAGE_ID, STRING...
#### Number parameters for inline variables

Example message from server: (4 byte rsc_id_one, 4 byte rsc_id_two, 4 byte rsc_id_three)
Example resource string 1: "You hit the %s%s with your %s"
Client displays resources in order.
Example resource string 2, same server message: "You use your %s$3 to hit the %s$0%s$1"
Client reorders the message so that rsc_id_one is in the third position and rsc_id_three is in the first. rsc_id_two is not reordered, but is skipped when displaying the resources. Any reordering done during a recursive CheckMessageOrder call is preserved (but does not affect anything outside the scope of its own call). If the %r has the number parameter, everything it references is moved to the new position.
#### Player description fixed-strings (age, guild, faction, etc.) sent as resources.

The fixed-strings at the top of the player description were previously sent in one string, after the actual editable description part and before the URL. This is now sent as (mostly) resources, so the client should process it as it would any other resource. The description drawing is handled by BP_USER_COMMAND sub-protocol UC_LOOK_PLAYER.
### KOD changes
- Any system that used AppendTempString to build up a string to send to the client has been modified to build a packet with resource IDs instead. This is most apparent in spell and item descriptions where the structure of the code for displaying the description has been completely changed.
- A new message in room.kod, SendCopyPacketAllInRoom(), has been added to use the C function SendCopyPacket() to send a packet to all users in the room, to avoid rebuilding packets where possible (the equivalent to sending everyone the same built-up temp string).
- The System object has a new table, phSkills, which keeps track of skills in the same way as spells. Previously skills were only kept as a list (likely due to the small number of them) but skill lookup is frequent enough to require a table (imo).
- RecalcLightAndWeather() in room.kod has been modified to make less message calls (calls which iterate through the same list). System.NewHour() calls this message and is one of the slowest frequently called messages.
- The LightDiscipleRobe class was nearly entirely duplicated from DiscipleRobe, and has been made a child class with the duplicated code removed. Also, all disciple robes now give 5 spellpower instead of 4 as the first level spellpower bonus to the same school (removing the unwanted scenario where an off-school robe is better for level 1).
- Added GetRegion() overrides to several rooms (performance).
- GetSpellAbility() and GetSkillAbility() in player.kod no longer make message calls (performance).
- Many areas of code have been converted to use else if or switches for performance reasons and/or code readability.

Several systems still need to be modified and will build up strings/temp strings to send to users. These systems will be affected by the server's language choice, so the server admin can default them to use either English or German. The systems not yet modified are:
- Quest NPC text.
- Guildmaster's war book and Caramo's Book of Jala (Justicar book).
- Honor strings (except the "newbie tag", which is sent as a resource separately).
- The frenzy War Event.
- Necromancer guild name (and guild/player names in general).
- Debug/GodLog strings.
- Cardinal/ordinal strings in system.kod.

### CODE REVIEW

**Comment by Meridian59** [comment]
I might want to include your multilanguage support in the main branch, too.  Here are a few thoughts after a brief look over the code:

- The Blakod does a lot of manual assembling of strings, which won't work for non-English languages.  In fact, often the order of parameters is different in different languages.  It would be nice to optionally number arguments like this:
"You hit the $1%s with the $2%s".  (In another language, $2 might precede $1 for the same string).  The client would match up the parameters by number. 

- It looks like the strings for all languages get written to the .rsc file, is that right?  Another option would be to have one output rsc per language and have the same string in every language share the same ID.  The client would fall back to the English rsc if there's no translation.  I haven't thought through all of the tradeoffs of this option, but it's typically what apps with good internationalization support do.

- Somewhat minor, but look at the mailnews DLL.  I tried to deal with replying to newsgroup messages from multiple languages, but I didn't do a very complete job of it.  That's why you'll sometimes see "Re: Aw: Re: Aw:" in the subject lines of newsgroup messages.  It would be nice to fix that up.

- Since changing language will be a very rare event, you might want to put it in the preferences menu instead of at the top level in the client.

**Comment by skittles1** [comment]
- The Blakod does a lot of manual assembling of strings, which won't work for non-English languages. In fact, often the order of parameters is different in different languages. It would be nice to optionally number arguments like this:
"You hit the $1%s with the $2%s". (In another language, $2 might precede $1 for the same string). The client would match up the parameters by number. 

I had originally planned to send the language choice to the server and store it in a player property, and each translation with different/out of order parameters would require a separate MsgSendUser call with the proper layout:
```
if piLang & PLANG_GERMAN
{
   % German MsgSendUser
}
else
{
   % English MsgSendUser
}
```
however I will see if I can modify the resource parameters in the way you've mentioned, as it's probably less work for translators/us to implement future translations.

- It looks like the strings for all languages get written to the .rsc file, is that right?

Yes, had looked into separate outputs but since the client uses a single .rsb file and loads all the resources into the same table it probably doesn't matter. All language strings of the same resource already share the same ID; the compiler now allows multiple strings per ID as long as they are in the same class and there are no duplicate strings for the same language.

- Somewhat minor, but look at the mailnews DLL.

Just had a look, should be easy enough to use the language config to send the right string while checking for all of them.

- Since changing language will be a very rare event, you might want to put it in the preferences menu instead of at the top level in the client.

Originally had it in the preferences menu (http://i.imgur.com/pLakf6O.png) however it's fairly difficult to work with if we add multiple languages with regards to spacing and such. Could add this as a sub-menu in Game or Options instead?

**Comment by Meridian59** [comment]
Some of these changes are kind of unfortunate, since now your Blakod is
very incompatible with the original server.  A change like for -> foreach
feels pretty gratuitous to me; it breaks compatibility without improving
things in my opinion.  The idea behind Blakod was to make it possible for
non-programmers to write game code, and it did that very well.  We
intentionally left out more complex features like pre/post increment,
switch statements, etc.  Maybe it will work out for your server since there
are only a very small number of people writing code, and they know C.

Mostly I would have liked the languages to stay the same so that I could
incorporate your game code bug fixes---that will take some extra work now.

I am happy to see that you have a system for other human languages (i.e.
German).

**Comment by Daenks** [comment]
We discussed the new KOD features and decided that they are so common across every beginner language that exists these days that it no longer makes a ton of difference. Plus to effectively code in KOD you already have to deal with an event system, OOP concepts, and all kinds of "programming" concepts.

I think the benefits outweigh the detriments in this case.

I can only speak for myself, but I think we would be willing to help you convert your kod code to this new format.

**Comment by treymd** [comment]
I used these regexes in notepad++ to flip all the fors to foreach to clear the way for the new for:

find: (for )(.*)(in )(.*)([\r\n]*)(.\s)\{
replace: foreach \2\3\4\5\6{

I probably had to manually rever 25 or som places where this regex changed a comment that happened to have a for, and it missed a couple actual fors, but not very many.  It could use improvement but it replaced over 1900 fors with foreach.  I had it converted in just a few hours. (including the time it took to tune these regexes)

**Comment by Meridian59** [comment]
I don't see the language changes as worth the amount of time it would take
for me to update everything.  With the amount of work you guys were doing,
it was probably inevitable that there would be a major incompatibility like
this at some point.

**Comment by skittles1** [comment]
At this point I think it might be worth considering adopting the Open Meridian repository in its entirety, and just disabling any changes you don't want (perhaps in a separate branch so you can pull in changes to master). There are so many quality of life changes (inventory sorting, group building, timers and descriptions on spells/items etc.), bug fixes (reflection AI, weapon damage/hitroll, client D3D renderer graphics, working Necromancer scenario) and new systems (client quest tab UI, stat reset, christmas decorations with falling snow particle effect) that might be wanted on 101/102 and most of it was already incompatible before the changes made in this pull request, or at least difficult to port over due to being built on top of other changes.

I'm not sure how closely you've been following our changes, but there's around 10 new C functions, the player object flags have been split up into 6 different fields, the .roo format is very different, our Send and Post can use string message names, SetString can create its own string, we have an %r string formatter for kod strings, etc. Anything ported over would likely have had issues with something in that list or some other change before new language features caused any problems.

I'm fairly sure the save games are compatible with our repo though quite a few commands would have to be run to fix various objects. If this is something you are interested in we do have the commands from each update saved (or I could write something to perform everything necessary).

**Pull request merged**
